### ISSUE TITLE
Question about bluetooth proximity.

### ISSUE THREAD

**Issue by lemonalemon** [ewenchou/bluetooth-proximity#3]
Hi Ewen!

I have to ask through github inevitably because there is a limited number of questions to ask on Twitter.

The first thing I want to ask is about the query you said.
I want to putting a longer wait time between queries, but I do not know what the query is in the code. What is a query?

The second question is to implement code that finds a larger RSSI value.
I stored two Bluetooth addresses in BT_ADDR_LIST.
I want to compare the RSSI values ​​of two Bluetooth addresses and implement code that finds a larger value depending on the situation. But I could not implement it.

At first, I tried to implement the method 'bluetooth_listen ()' by dividing b, which is a variable, into two variables b and c, and storing each address separately.
Ex)
B = BluetoothRSSI (addr = first Bluetooth address)
C = BluetoothRSSI (addr = second Bluetooth address)
But I failed.

In the next method I tried creating two threads. However, I do not know how to call the RSSI value of each thread from the main function.
Ex)
Th1 = start_thread (addr = first Bluetooth address, callback = dummy_callback)
Th2 = start_thread (addr = second Bluetooth address, callback = dummy_callback)
This also failed.

So I try to get some advice.
I do not use Alexa, but I want to use your source for a similar purpose.
Can I see what I want?

**Comment by ewenchou** [comment]
The "query" is done in the method `get_rssi()` 
For what you're trying to do, the example script probably isn't what you want. To get the values for two different bluetooth addresses you could so something like below (extend it to do more as you need).

```
from bt_proximity import BluetoothRSSI

device_1 = BluetoothRSSI(addr="first address goes here")
device_2 = BluetoothRSSI(addr="second address goes here")

# If scan is unsuccessful, the value will be `None`
# So only do comparison if both values are not None otherwise you'll get an exception
value_1 = device_1.get_rssi()
value_2 = device_2.get_rssi()
```
