### ISSUE TITLE
is it really working?

### ISSUE THREAD

**Issue by netikras** [ewenchou/bluetooth-proximity#4]
![image](https://user-images.githubusercontent.com/2045031/30148338-b36311a0-93ab-11e7-8921-e2b4692cce82.png)

this is what I get with my phone BT disabled.

The very same thing I get with BT enabled.

Does that mean it's working?

**Comment by ewenchou** [comment]
It's working in the sense that you are getting a value returned. If the RSSI scan failed, the value would be `None` instead.

If you turned off bluetooth, the value should be `None`. Are you sure you entered the correct bluetooth address?

**Comment by netikras** [comment]
Yepp, I'm pretty sure.

pc-045 ~ $ hcitool name 78:00:9E:4B:E4:E1
Samsung Galaxy S7 edge
pc-045 ~ $

**Comment by ewenchou** [comment]
I think it is working, however cannot explain why the values are the same when you have the bluetooth disabled. When I disable bluetooth, I will get a `None` value returned. Perhaps you can try a different device if you get a chance.
