### ISSUE TITLE
Bluetooth Low Energy device

### ISSUE THREAD

**Issue by Sadafaga** [ewenchou/bluetooth-proximity#5]
Hello,

I have a problem when I try to use the program 'bluetooth_scanner.py' into a Bluetooth Low Energy device. The fact is that rssi value is always 'none' and I know that is not 'none'.  Do you have a solution about that?

Thanks.

**Comment by ewenchou** [comment]
I was not able to get my BT adapter to work with Bluetooth LE. I think it is either a limitation of the USB adapter I have, or the drivers I used on RPi. Right now, seems this code will not work with BT LE. Sorry.
