### ISSUE TITLE
problems with close range

### ISSUE THREAD

**Issue by jaredglastetter** [ewenchou/bluetooth-proximity#6]
Hey im having a problem while testing test_address.py where i get 0 about 95% of the time in my room unless im moving the device(samsung A5). if i move the device around it moves around values between 1 and 7 and sometimes jumps to around 12, but as soon as it stops it goes back to 0.(sometimes i still get 0 while moving it)

ill take it out of the room and it will go to around 25 and then by the time i get back to my room i get 0s for the rest of the time (might have something to do with the request max issue the other user was having)

There is a wireless device somewhere in my apartment building (maybe speakers?) that i connected to just out of curiosity and it hovers at about 19-24 consistently and never drops to 0.

in your experience has this worked nicely in short ranges? also do you think this is a sufficient solution for long periods of time. (polling every second for hours )

Thanks!

**Comment by ewenchou** [comment]
It also stays at zero for me when I’m within 1-2 ft of my Raspberry Pi. It also depends what is around it, e.g. when I move behind couch the value goes up a lot. I think it’s a limitation of how strong the Bluetooth device’s is and the surroundings.
