### ISSUE TITLE
Not working on python 3 

### ISSUE THREAD

**Issue by derfloDev** [ewenchou/bluetooth-proximity#7]
Can you help me getting this to work under python 3 ?

`reqstr = struct.pack("6sB17s", bt.str2ba(self.addr), bt.ACL_LINK, "\0" * 17)`
 `request = array.array("c", reqstr)`

This is not working in python 3.

**Comment by voglster** [comment]
reqstr = struct.pack("6sB17s", bt.str2ba(self.addr), bt.ACL_LINK, b"\0" * 17)
request = array.array("B", reqstr)

worked for me

**Comment by ewenchou** [comment]
Thanks @voglster for the workaround
Thanks @aude for the Python 3 fork
